alias s="source ~/.zshrc"
alias ls="gls --color=auto"     # require `brew install coreutils`
alias la="ls -a"
alias ll="ls -l"
alias lla="ll -a"
alias vi="vim"
alias em="emacs"
alias more="less"
alias ip-release="sudo ipconfig set en0 BOOTP"
alias ip-new="sudo ipconfig set en0 DHCP"
alias cp="cp -p"
alias mkdir="mkdir -p"
alias x="exit"
alias ht="cd ~/htdocs"
alias ws="cd ~/Dropbox/workspace"
alias g="git"
alias mysql="mysql --pager='less -S -n -i -F -X' --auto-rehash"
alias pst="pstorm"
alias mv="mv -i"
alias rm="gmv -f -b -t ~/.Trash"    # require `brew install coreutils`
alias api="php bootstrap/api.php"
alias web="php bootstrap/web.php"
alias chm="open -a \"Google Chrome\""
alias diff="vimdiff"
alias hubb="hub browse"
alias hubpr="hub pull-request"
alias atom="open -a Atom"
alias docker-cleani="docker images | grep '^<none>' | awk '{print $3}' | xargs docker rmi -f"
alias docker-clean="docker ps -f status=exited -q | xargs docker rm"

