alias s="source ~/.zshrc"
alias ls="gls --color=auto"
alias la="ls -a"
alias ll="ls -l"
alias lla="ll -a"
alias vi="vim"
alias em="emacs"
alias more="less"
alias ip="ifconfig"
alias cp="cp -p"
alias mkdir="mkdir -p"
alias x="exit"
alias ht="cd ~/workspace/htdocs"
alias dt="cd ~/Dropbox/Sync/dotfiles"
alias console="php app/console"
alias g="git"
alias mysql="mysql --auto-rehash"
alias pst="pstorm"
